spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/bear?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
  redis:
    host: localhost
    port: 6379
springdoc:
  version: v1.0.0
  swagger-ui:
    path: /api-docs