name: PR ArchUnit & Lint Check

on:
  pull_request:
    branches: [ develop ]

jobs:
  check:
    name: Run ArchUnit + Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Run ArchUnit tests
        run: ./gradlew archUnitTest

      - name: Run Lint (replace with ktlintCheck/detekt/lint)
        run: ./gradlew lint
