name: JIRA Ticket Validation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - develop # Target branch, we cannot check develop to main.

jobs:
  jira-ticket-check:
    runs-on: ubuntu-latest

    steps:
      - name: Validate JIRA ticket in PR title
        uses: actions/github-script@v7
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const match = prTitle.match(/\[(KAN-\d+)\]/);

            if (!match) {
              core.setFailed("❌ PR 제목에 '[KAN-123]' 형식의 JIRA 티켓이 포함되어야 해요.");
              return;
            }

            const ticket = match[1];
            const url = `${process.env.JIRA_BASE_URL}/rest/api/3/issue/${ticket}`;
            const auth = Buffer.from(`${process.env.JIRA_EMAIL}:${process.env.JIRA_API_TOKEN}`).toString('base64');

            const response = await fetch(url, {
              method: 'GET',
              headers: {
                'Authorization': `Basic ${auth}`,
                'Accept': 'application/json'
              }
            });

            if (response.status === 404) {
              core.setFailed(`❌ JIRA 티켓 '${ticket}'이 존재하지 않아요.`);
            } else if (!response.ok) {
              core.setFailed(`❌ JIRA API 호출 오류가 발생했어요. ${response.status} ${response.statusText}`);
            } else {
              console.log(`✅ 유효한 JIRA 티켓: ${ticket}`);
            }
